# Generated by Django 5.2.8 on 2025-11-30 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Przedmiot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("klasyfikacja", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Uczen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=255)),
                ("nazwisko", models.CharField(max_length=255)),
                ("pesel", models.CharField(max_length=255)),
                ("klasa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ocena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocena", models.PositiveIntegerField()),
                ("data_wystawienia", models.DateField()),
                (
                    "przedmiot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocenyapp.przedmiot",
                    ),
                ),
                (
                    "uczen_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ocenyapp.uczen"
                    ),
                ),
            ],
        ),
    ]
