# Generated by Django 5.2.8 on 2025-11-30 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ryby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200)),
                ("występowanie", models.CharField(max_length=200)),
                ("styl_zycia", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="okres_ochronny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("od_miesiaca", models.IntegerField()),
                ("do_miesiaca", models.IntegerField()),
                ("wymiar_ochrony", models.IntegerField()),
                (
                    "ryby_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rybyapp.ryby"
                    ),
                ),
            ],
        ),
    ]
